baseURL = "https://alexandrion-coins.github.io/coins-dacia"
title = "Roman Empire Coins"
theme = "showcase"

[taxonomies]
  country = "countries"
  material = "materials"
  grade = "grades"

[params]
  description = "DACIA ROMANA"
  author = "Alexandrion"
  darkMode = true

[security.node.permissions]
disable = true
